CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "core_activitylog" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "message" text NOT NULL, "created_at" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "core_newsandevents" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(200) NOT NULL, "summary" text NOT NULL, "posted_as" varchar(10) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "core_session" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL UNIQUE, "is_current" bool NOT NULL, "next_session_begins" date NULL, "created_at" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "core_semester" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "semester" varchar(10) NOT NULL, "is_current" bool NOT NULL, "next_semester_begins" date NULL, "created_at" datetime NOT NULL, "session_id" bigint NULL REFERENCES "core_session" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "core_activitylog_created_at_0dcde50a" ON "core_activitylog" ("created_at");
CREATE INDEX "core_activi_created_3d0bd9_idx" ON "core_activitylog" ("created_at" DESC);
CREATE INDEX "core_newsan_posted__71e665_idx" ON "core_newsandevents" ("posted_as");
CREATE INDEX "core_newsan_created_c318d8_idx" ON "core_newsandevents" ("created_at" DESC);
CREATE INDEX "core_sessio_is_curr_9e5e48_idx" ON "core_session" ("is_current");
CREATE INDEX "core_sessio_name_8fee95_idx" ON "core_session" ("name");
CREATE INDEX "core_semester_session_id_5eb6ae4a" ON "core_semester" ("session_id");
CREATE INDEX "core_semest_semeste_e63ff0_idx" ON "core_semester" ("semester");
CREATE INDEX "core_semest_is_curr_37b6e8_idx" ON "core_semester" ("is_current");
CREATE INDEX "core_semest_session_a73f2c_idx" ON "core_semester" ("session_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "accounts_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "role" varchar(20) NOT NULL, "phone" varchar(40) NULL, "picture" varchar(100) NULL, "email" varchar(254) NULL);
CREATE TABLE IF NOT EXISTS "accounts_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "accounts_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "accounts_user_groups_user_id_group_id_59c0b32f_uniq" ON "accounts_user_groups" ("user_id", "group_id");
CREATE INDEX "accounts_user_groups_user_id_52b62117" ON "accounts_user_groups" ("user_id");
CREATE INDEX "accounts_user_groups_group_id_bd11a704" ON "accounts_user_groups" ("group_id");
CREATE UNIQUE INDEX "accounts_user_user_permissions_user_id_permission_id_2ab516c2_uniq" ON "accounts_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "accounts_user_user_permissions_user_id_e4f0a161" ON "accounts_user_user_permissions" ("user_id");
CREATE INDEX "accounts_user_user_permissions_permission_id_113bb443" ON "accounts_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "courses_program" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(150) NOT NULL UNIQUE, "summary" text NOT NULL);
CREATE TABLE IF NOT EXISTS "courses_course" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "slug" varchar(50) NOT NULL UNIQUE, "title" varchar(200) NOT NULL, "code" varchar(200) NOT NULL UNIQUE, "credit" integer unsigned NOT NULL CHECK ("credit" >= 0), "summary" text NOT NULL, "level" varchar(25) NOT NULL, "year" smallint unsigned NOT NULL CHECK ("year" >= 0), "semester" varchar(200) NOT NULL, "is_elective" bool NOT NULL, "instructor_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "program_id" bigint NOT NULL REFERENCES "courses_program" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_course_students" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_courseallocation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "lecturer_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "session_id" bigint NULL REFERENCES "core_session" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_courseallocation_courses" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "courseallocation_id" bigint NOT NULL REFERENCES "courses_courseallocation" ("id") DEFERRABLE INITIALLY DEFERRED, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_courseoffer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "dep_head_id" bigint NOT NULL REFERENCES "accounts_departmenthead" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_upload" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(100) NOT NULL, "file" varchar(100) NOT NULL, "updated_date" datetime NOT NULL, "upload_time" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_uploadvideo" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(100) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "video" varchar(100) NOT NULL, "summary" text NOT NULL, "timestamp" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_courseoffering" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "is_elective" bool NOT NULL, "capacity" integer unsigned NULL CHECK ("capacity" >= 0), "created_at" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED, "instructor_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "semester_id" bigint NULL REFERENCES "core_semester" ("id") DEFERRABLE INITIALLY DEFERRED, "session_id" bigint NULL REFERENCES "core_session" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_courseoffering_students" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "courseoffering_id" bigint NOT NULL REFERENCES "courses_courseoffering" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "courses_course_instructor_id_5b0643dc" ON "courses_course" ("instructor_id");
CREATE INDEX "courses_course_program_id_7e46afed" ON "courses_course" ("program_id");
CREATE UNIQUE INDEX "courses_course_students_course_id_user_id_8f9097c6_uniq" ON "courses_course_students" ("course_id", "user_id");
CREATE INDEX "courses_course_students_course_id_2c36f816" ON "courses_course_students" ("course_id");
CREATE INDEX "courses_course_students_user_id_7e195ad6" ON "courses_course_students" ("user_id");
CREATE INDEX "courses_courseallocation_lecturer_id_082280e1" ON "courses_courseallocation" ("lecturer_id");
CREATE INDEX "courses_courseallocation_session_id_1ef4bf65" ON "courses_courseallocation" ("session_id");
CREATE UNIQUE INDEX "courses_courseallocation_courses_courseallocation_id_course_id_bb548c8d_uniq" ON "courses_courseallocation_courses" ("courseallocation_id", "course_id");
CREATE INDEX "courses_courseallocation_courses_courseallocation_id_8a8a4163" ON "courses_courseallocation_courses" ("courseallocation_id");
CREATE INDEX "courses_courseallocation_courses_course_id_d19f2a21" ON "courses_courseallocation_courses" ("course_id");
CREATE INDEX "courses_courseoffer_dep_head_id_176ffa27" ON "courses_courseoffer" ("dep_head_id");
CREATE INDEX "courses_upload_course_id_b958e9bd" ON "courses_upload" ("course_id");
CREATE INDEX "courses_uploadvideo_course_id_4195c71c" ON "courses_uploadvideo" ("course_id");
CREATE INDEX "courses_courseoffering_course_id_e8fae9f7" ON "courses_courseoffering" ("course_id");
CREATE INDEX "courses_courseoffering_instructor_id_1a8e9a89" ON "courses_courseoffering" ("instructor_id");
CREATE INDEX "courses_courseoffering_semester_id_eb8e4ced" ON "courses_courseoffering" ("semester_id");
CREATE INDEX "courses_courseoffering_session_id_944988c1" ON "courses_courseoffering" ("session_id");
CREATE INDEX "courses_cou_session_b938cb_idx" ON "courses_courseoffering" ("session_id", "semester_id");
CREATE INDEX "courses_cou_course__cb6dcf_idx" ON "courses_courseoffering" ("course_id");
CREATE UNIQUE INDEX "courses_courseoffering_students_courseoffering_id_user_id_c0c90780_uniq" ON "courses_courseoffering_students" ("courseoffering_id", "user_id");
CREATE INDEX "courses_courseoffering_students_courseoffering_id_ce618338" ON "courses_courseoffering_students" ("courseoffering_id");
CREATE INDEX "courses_courseoffering_students_user_id_799b02e0" ON "courses_courseoffering_students" ("user_id");
CREATE TABLE IF NOT EXISTS "accounts_departmenthead" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "department_id" bigint NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL UNIQUE REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "accounts_departmenthead_department_id_35df83b0" ON "accounts_departmenthead" ("department_id");
CREATE TABLE IF NOT EXISTS "accounts_parent" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "phone" varchar(60) NULL, "email" varchar(254) NULL, "user_id" bigint NOT NULL UNIQUE REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "accounts_student" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "level" varchar(25) NULL, "program_id" bigint NULL REFERENCES "courses_program" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL UNIQUE REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "accounts_student_program_id_cbc959aa" ON "accounts_student" ("program_id");
CREATE TABLE IF NOT EXISTS "accounts_parent_students" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "parent_id" bigint NOT NULL REFERENCES "accounts_parent" ("id") DEFERRABLE INITIALLY DEFERRED, "student_id" bigint NOT NULL REFERENCES "accounts_student" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "accounts_parent_students_parent_id_student_id_de8e9782_uniq" ON "accounts_parent_students" ("parent_id", "student_id");
CREATE INDEX "accounts_parent_students_parent_id_f521674d" ON "accounts_parent_students" ("parent_id");
CREATE INDEX "accounts_parent_students_student_id_cf4ed7d4" ON "accounts_parent_students" ("student_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "quizzes_choice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "text" varchar(255) NOT NULL, "is_correct" bool NOT NULL, "question_id" bigint NOT NULL REFERENCES "quizzes_question" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "quizzes_quiz" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(200) NOT NULL, "description" text NOT NULL, "random_order" bool NOT NULL, "single_attempt" bool NOT NULL, "pass_mark" smallint unsigned NOT NULL CHECK ("pass_mark" >= 0), "draft" bool NOT NULL, "created_at" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "quizzes_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "text" text NOT NULL, "order" integer unsigned NOT NULL CHECK ("order" >= 0), "type" varchar(4) NOT NULL, "quiz_id" bigint NOT NULL REFERENCES "quizzes_quiz" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "quizzes_choice_question_id_46d39dbb" ON "quizzes_choice" ("question_id");
CREATE INDEX "quizzes_quiz_course_id_6476d9c4" ON "quizzes_quiz" ("course_id");
CREATE INDEX "quizzes_question_quiz_id_70961654" ON "quizzes_question" ("quiz_id");
CREATE TABLE IF NOT EXISTS "quizzes_quizattempt" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "attempt_number" integer unsigned NOT NULL CHECK ("attempt_number" >= 0), "started_at" datetime NULL, "completed_at" datetime NULL, "score" decimal NULL, "quiz_id" bigint NOT NULL REFERENCES "quizzes_quiz" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "quizzes_answer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "free_response" text NULL, "selected_choice_id" bigint NULL REFERENCES "quizzes_choice" ("id") DEFERRABLE INITIALLY DEFERRED, "question_id" bigint NOT NULL REFERENCES "quizzes_question" ("id") DEFERRABLE INITIALLY DEFERRED, "attempt_id" bigint NOT NULL REFERENCES "quizzes_quizattempt" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "qa_quiz_user_idx" ON "quizzes_quizattempt" ("quiz_id", "user_id");
CREATE UNIQUE INDEX "quizzes_answer_attempt_id_question_id_db0a71c7_uniq" ON "quizzes_answer" ("attempt_id", "question_id");
CREATE INDEX "quizzes_quizattempt_quiz_id_da54d53d" ON "quizzes_quizattempt" ("quiz_id");
CREATE INDEX "quizzes_quizattempt_user_id_e9ee8fc7" ON "quizzes_quizattempt" ("user_id");
CREATE INDEX "quizzes_answer_selected_choice_id_f0a4a00d" ON "quizzes_answer" ("selected_choice_id");
CREATE INDEX "quizzes_answer_question_id_7e471477" ON "quizzes_answer" ("question_id");
CREATE INDEX "quizzes_answer_attempt_id_edb0a031" ON "quizzes_answer" ("attempt_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
