# Generated by Django 5.2.3 on 2025-09-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx'), models.Index(fields=['level'], name='core_activi_level_861e1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsAndEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, max_length=200)),
                ('posted_as', models.CharField(choices=[('news', 'News'), ('event', 'Event')], default='news', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News / Event',
                'verbose_name_plural': 'News / Events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['posted_as'], name='core_newsan_posted__71e665_idx'), models.Index(fields=['-created_at'], name='core_newsan_created_c318d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_current', models.BooleanField(default=False)),
                ('next_session_begins', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_current'], name='core_sessio_is_curr_9e5e48_idx'), models.Index(fields=['name'], name='core_sessio_name_8fee95_idx')],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], max_length=10)),
                ('is_current', models.BooleanField(default=False)),
                ('next_semester_begins', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.session')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['semester'], name='core_semest_semeste_e63ff0_idx'), models.Index(fields=['is_current'], name='core_semest_is_curr_37b6e8_idx'), models.Index(fields=['session'], name='core_semest_session_a73f2c_idx')],
            },
        ),
    ]
