# Generated by Django 5.2.3 on 2025-09-17 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activitylog_newsandevents_semester_session'),
        ('courses', '0010_program_remove_userlessonprogress_enrollment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='sitefeedback',
            name='user',
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='newsandevents',
            index=models.Index(fields=['posted_as'], name='core_newsan_posted__71e665_idx'),
        ),
        migrations.AddIndex(
            model_name='newsandevents',
            index=models.Index(fields=['-created_at'], name='core_newsan_created_c318d8_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_current'], name='core_sessio_is_curr_9e5e48_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['name'], name='core_sessio_name_8fee95_idx'),
        ),
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.session'),
        ),
        migrations.DeleteModel(
            name='SiteFeedback',
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['semester'], name='core_semest_semeste_e63ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['is_current'], name='core_semest_is_curr_37b6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['session'], name='core_semest_session_a73f2c_idx'),
        ),
    ]
