# Generated by Django 5.2.3 on 2025-06-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
