# Generated by Django 5.2.3 on 2025-08-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pictures/%y/%m/%d/'),
        ),
    ]
