# Generated by Django 5.2.3 on 2025-09-19 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_category_remove_sitefeedback_user_and_more'),
        ('courses', '0011_create_courseoffering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=1),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['session', 'semester'], name='courses_cou_session_b938cb_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['course'], name='courses_cou_course__cb6dcf_idx'),
        ),
    ]
